### ISSUE TITLE
answer

### ISSUE THREAD

**Issue by macMikey** [macMikey/LCB-missing-manual#10]

**Comment by macMikey** [comment]
`execute script`?

**Comment by bwmilby** [comment]
See `public handler OnClick() returns nothing` in the TreeView widget source code.  Here's the lines where it is actually used:

```
put "Really delete array element at path [" & the result & "]?" into tPrompt
execute script "answer \q" & tPrompt & "\q with \qOK\q and \qCancel\q; return it"
if the result is "OK" then
   removePath(tData["path"])
end if
```

**Comment by macMikey** [comment]
thanks!

**Comment by macMikey** [comment]
well, this fails
`execute script "answer \q" & "test" & "\q with \qOK\q and \qCancel\q; return it"`
with "Script access not allowed"

**Comment by bwmilby** [comment]
See my comment on issue #14

**Comment by BerndN** [comment]
> execute script "answer \q" & "test" & "\q with \qOK\q and \qCancel\q; return it"

that works for me in a onMouseDown handler

I think "execute" is also not permitted within a onPaint handler (that includes the handler called during onPaint)

**Comment by macMikey** [comment]
Bernd has entered the chat!
Yes, thank you, I see a note in the Dictionary about that, now.
