### ISSUE TITLE
case-sensitivity inconsistencies

### ISSUE THREAD

**Issue by macMikey** [macMikey/LCB-missing-manual#13]
It looks like types have to be Capitalized
```
Type
  : <Name: Identifier>
  | 'optional' <Target: Type>
  | 'any'
  | 'nothing'
  | 'Boolean'
  | 'Integer'
  | 'Real'
  | 'Number'
  | 'String'
  | 'Data'
  | 'Array'
  | 'List'
  | 'Pointer'
```
BUT, i have to check `is a` with lowercase, e.g. `is a number`

**Comment by bwmilby** [comment]
I think that is just the syntax.  "is a boolean" is an operator.

**Comment by macMikey** [comment]
that won't be confusing at all, when someone is going to think they should type `is a Boolean`
