### ISSUE TITLE
message box

### ISSUE THREAD

**Issue by macMikey** [macMikey/LCB-missing-manual#14]
this does not work:
```
private handler Message ( in pPrompt as String, in pBeforeAfterInto as String ) returns nothing
	execute script "put \q" & pPrompt & "\q" && pBeforeAfterInto && "msg"
end handler
```
I get **Script access not allowed**

**Comment by bwmilby** [comment]
do you have `use com.livecode.engine` in the code?

**Comment by macMikey** [comment]
yes.
I'm working on NavRAD, so it looks like it's got all the USE lines in it.

**Comment by bwmilby** [comment]
Ok, the error is from the IDE and not the compiler.  I'm getting the same thing.

**Comment by bwmilby** [comment]
This issue is where/when you are attempting to use script access.  Where in the flow of the widget creation are you calling that handler?

**Comment by macMikey** [comment]
In `OnLoad()` to debug the value of a property, since I don't think we have a real debugger in lcb
So I took that one out, and I have one in `CalculateIconRects()`, which is called in `OnCreate()`, but that's also throwing the error, so I'm guessing it's still too early.

**Comment by bwmilby** [comment]
Yes, I would infer that until the widget is fully created that you can’t use the script.  The message is going to the script object.
