### ISSUE TITLE
[property metadata] default does what, exactly?

### ISSUE THREAD

**Issue by macMikey** [macMikey/LCB-missing-manual#22]
```
property "test" get mTest set setTest
metadata test.default is "test"
metadata test.editor is "com.livecode.pi.string"
metadata test.label is "Test"

private variable mTest as String

handler setTest(in pTest as String) returns nothing
	put "test" into mTest
end handler
```
if I open the PI, the value is blank, even though a default is set. does the default value get set when the PI closes, if no value is assigned?

**Comment by macMikey** [comment]
if i assign a value in onLoad(), the value is displayed in this case

**Comment by macMikey** [comment]
I see lots of default values, but when I look in the PI's, including the specific PI's for the properties, I am not finding the code for managing the defaults, yet, anyway.

**Comment by macMikey** [comment]
it seems like it's only for use with the right-click "Reset to default" option in the PI

**Comment by BerndN** [comment]
I tried your property and handler and it worked for me.???

> handler setTest(in pTest as String) returns nothing
> 	put "test" into mTest
> end handler

that handler is used by the PI to change the variable mTest. The default value is set by the definition in the property metadata without handler setTest.

**Comment by macMikey** [comment]
i closed because it seems to be specific to the navrad widget, which is where i was testing (trying to find another problem in the widget)
i took this code and threw it in a much smaller/shorter widget, and it worked as one would expect.
so i think there's something going in in the navrad/navbar that is interfering, but doing it quietly.
i have already discovered that there are other fails that are silent, like if you declare a String variable and then try to `format as string`, the same variable. it will fail, and stop execution of the handler, but not throw an error.
