### ISSUE TITLE
Custom Property Editor - location, how to cause it to load?

### ISSUE THREAD

**Issue by macMikey** [macMikey/LCB-missing-manual#38]
* Several of the new widgets have an *editors* folder, with their PE stack and the PE behavior stack
* What is the the mechanism to cause those to load?

**Comment by macMikey** [comment]
the stack exists in the *editors* subfolder, the way it does for the PB/PL/PG
what doesn't work:
`metadata itemArray.editor is "/editors/com.livecode.pi.navRAD"`
`metadata itemArray.editor is "editors/com.livecode.pi.navRAD"`

**Comment by macMikey** [comment]
found  in `revInspectorBehavior.livecodescript`:
```
   # open editor stack if it exists
   if there is not a file tEditorStackPath then 
      # check if an extension has provided its own editor
      # it is named <id>.editor.editorName
      local tId, tPath
      set the itemdelimiter to "."
      put item 1 to -3 of pEditor into tId
      put revIDEExtensionProperty(tId, "install_path") into tPath
      put tPath & "/editors/" & pEditor & ".livecode" into tEditorStackPath
      put tPath & "/editors/" & pEditor & ".behavior.livecodescript" into tEditorBehaviorPath
   end if
```
so the rule is:
1. put it in the *editors* folder at the level of the `.lcb` file
2. the name doesn't really matter.
if the editor stack name is 
*com.livecode.widget.navRad.editor.navData.livecode*
then the behavior is
*com.livecode.widget.navRad.editor.navData.behavior.livecodescript*
and the **use** line is
`metadata itemArray.editor is "com.livecode.widget.navRad.editor.navData"`

**Comment by BerndN** [comment]
Bravo.

**Comment by macMikey** [comment]
[documented in the wiki](https://github.com/macMikey/LCB-missing-manual/wiki/Property-Editors)
